=== er-deepak-ram/validate-json/json_files/schema.json
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "title": "Update Status v1.1.3",
  "type": "object",
  "required": [
    "schema",
    "brand",
    "market",
    "uuid",
    "sender",
    "vehicle",
    "updateEcosys"
  ],
  "additionalProperties": false,
  "properties": {
    "schema": {
      "type": "object",
      "required": [
        "name",
        "version"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "enum": ["updatestatus"]
        },
        "version": {
          "enum": ["1.1.3"]
        }
      }
    },
    "brand": {
      "enum": ["audi", "vw", "porsche", "seat", "skoda", "vwn", "bentley", "lamborghini", "man", "man-la", "bugatti", "ducati", "faw-vw", "svw", "faw-audi", "svw-audi", "svw-skoda", "anhui-vw", "ford"]
    },
    "market": {
      "enum": ["eu", "cn", "nar"]
    },
    "uuid": {
      "type": "string",
      "format": "uuid"
    },
    "sourceEventsUUIDs": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string",
          "format": "uuid"
        }
      }
    },
    "sender": {
      "type": "object",
      "required": [
        "id",
        "dtime"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "object",
          "required": [
            "type",
            "val"
          ],
          "additionalProperties": false,
          "properties": {
            "type": {
              "enum": ["APP-ID", "ICTO-NR", "LeanIX-ID", "CUSTOM"]
            },
            "val": {
              "type": "string"
            }
          }
        },
        "dtime": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.\\d{7}Z$"
        }
      }
    },
    "origin": {
      "type": "object",
      "required": ["source", "dtime"],
      "additionalProperties": false,
      "properties": {
        "source": {
          "enum": ["vehicle", "backend"]
        },
        "dtime": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.\\d{7}Z$"
        }
      }
    },
    "vehicle": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "type": "object",
          "required": [
            "type",
            "val"
          ],
          "additionalProperties": false,
          "properties": {
            "type": {
              "enum": ["vin", "pseudonym", "pseudonym-unified"]
            },
            "val": {
              "type": "string"
            }
          }
        },
        "time": {
          "type": "string"
        }
      }
    },
    "updateEcosys": {
      "type": "object",
      "required": [
        "id",
        "uc"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "object",
          "required": [
            "val"
          ],
          "additionalProperties": false,
          "properties": {
            "val": {
              "enum": ["e3-1.2-orunext", "e3-2.0-orunext", "e3-1.2-autoedge", "e3-1.1-oru4", "e3-1.1-mod4", "mod3", "oru2/3"]
            }
          }
        },
        "uc": {
          "type": "object",
          "required": [
            "id",
            "exec",
            "vehicleEvent"
          ],
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": "object",
              "required": [
                "type",
                "val"
              ],
              "additionalProperties": false,
              "properties": {
                "type": {
                  "enum": ["custom", "dlcm-bluelayer", "production"]
                },
                "val": {
                  "enum": ["recall", "bugfix", "upgrade", "testrecall"]
                }
              }
            },
            "exec": {
              "type": "object",
              "required": [
                "id"
              ],
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "object",
                  "required": [
                    "val"
                  ],
                  "additionalProperties": false,
                  "properties": {
                    "val": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "campaign": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "val": {
                      "type": "string"
                    }
                  }
                },
                "recall": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "action": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "id": {
                          "type": "object",
                          "additionalProperties": false,
                          "properties": {
                            "val": {
                              "type": "string"
                            }
                          }
                        },
                        "criterion": {
                          "type": "object",
                          "additionalProperties": false,
                          "properties": {
                            "id": {
                              "type": "object",
                              "additionalProperties": false,
                              "properties": {
                                "val": {
                                  "type": "string"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "svc42ChangeMeasure": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "id": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "val": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "batch": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "id": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "val": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            },
            "vehicleEvent": {
              "type": "object",
              "required": [
                "raw"
              ],
              "additionalProperties": false,
              "properties": {
                "key": {
                  "enum": [
                    "canceled", "created", "documented", "failed", "offboardPrepped", "onboardPrepped", "success", "updated", "uptodate"
                  ]
                },
                "raw": {
                  "type": "string"
                },
                "message": {
                  "type": "object"
                }
              }
            }
          }
        },
        "release": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "val": {
                  "type": "string"
                }
              }
            },
            "version": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "val": {
                  "type": "string"
                }
              }
            },
            "notes": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "val": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== er-deepak-ram/validate-json/json_files/BVWCVWAUZ22053101 1.json
[
    {
        "schema": {
            "name": "updatestatus",
            "version": "1.1.3"
        },
        "brand": "vw",
        "market": "eu",
        "uuid": "4dabbbc2-fcb2-4074-a91c-5e2977a5bbf8",
        "sender": {
            "id": {
                "type": "CUSTOM",
                "val": "WCDP_ORUEN"
            },
            "dtime": "2024-03-20T13:10:08.3722639Z"
        },
        "origin": {
            "source": "backend",
            "dtime": "2024-03-20T14:37:15.0939400Z"
        },
        "vehicle": {
            "id": {
                "type": "vin",
                "val": "BVWCVWAUZ22053101"
            }
        },
        "updateEcosys": {
            "id": {
                "val": "e3-1.1-oru4"
            },
            "uc": {
                "id": {
                    "type": "custom",
                    "val": "upgrade"
                },
                "exec": {
                    "id": {
                        "val": "0"
                    }
                },
                "campaign": {
                    "id": {
                        "val": "RECALL_OUG6_A3_10001164_485DDF5413A04C2DAA40EF6892982D7F"
                    },
                    "recall": {
                        "action": {
                            "id": {
                                "val": "OUG6"
                            },
                            "criterion": {
                                "id": {
                                    "val": "A3"
                                }
                            }
                        }
                    },
                    "svc42ChangeMeasure": {
                        "id": {
                            "val": "003"
                        }
                    },
                    "batch": {
                        "id": {
                            "val": "485DDF5413A04C2DAA40EF6892982D7F"
                        }
                    }
                },
                "vehicleEvent": {
                    "key": "created",
                    "raw": "VEHICLE_ASSIGNED_TO_CAMPAIGN",
                    "message": {
                        "text": "A vehicle is now eligible for an update"
                    }
                }
            },
            "release": {
                "id": {
                    "val": "85H110100A"
                },
                "version": {
                    "val": "1015"
                },
                "notes": {
                    "id": {
                        "val": "rn-2023-09-06-test"
                    }
                }
            }
        }
    },
	{
        "schema": {
            "name": "updatestatus",
            "version": "1.1.3"
        },
        "brand": "vw",
        "market": "eu",
        "uuid": "078ec231-88bc-4d74-9774-96c0b820ceda",
        "sender": {
            "id": {
                "type": "CUSTOM",
                "val": "WCDP_ORUEN"
            },
            "dtime": "2024-03-20T13:10:08.3722639Z"
        },
        "origin": {
            "source": "backend",
            "dtime": "2024-03-20T14:37:15.0939400Z"
        },
        "vehicle": {
            "id": {
                "type": "vin",
                "val": "BVWCVWAUZ22053101"
            }
        },
        "updateEcosys": {
            "id": {
                "val": "e3-1.1-oru4"
            },
            "uc": {
                "id": {
                    "type": "custom",
                    "val": "upgrade"
                },
                "exec": {
                    "id": {
                        "val": "0"
                    }
                },
                "campaign": {
                    "id": {
                        "val": "RECALL_OUG6_A3_10001164_485DDF5413A04C2DAA40EF6892982D7F"
                    },
                    "recall": {
                        "action": {
                            "id": {
                                "val": "OUG6"
                            },
                            "criterion": {
                                "id": {
                                    "val": "A3"
                                }
                            }
                        }
                    },
                    "svc42ChangeMeasure": {
                        "id": {
                            "val": "003"
                        }
                    },
                    "batch": {
                        "id": {
                            "val": "485DDF5413A04C2DAA40EF6892982D7F"
                        }
                    }
                },
                "vehicleEvent": {
                    "key": "offboardPrepped",
                    "raw": "DD_SENT",
                    "message": {
                        "text": "Preparation on backend side are finished"
                    }
                }
            },
            "release": {
                "id": {
                    "val": "85H110100A"
                },
                "version": {
                    "val": "1015"
                },
                "notes": {
                    "id": {
                        "val": "rn-2023-09-06-test"
                    }
                }
            }
        }
    },
	{
        "schema": {
            "name": "updatestatus",
            "version": "1.1.3"
        },
        "brand": "vw",
        "market": "eu",
        "uuid": "726638fa-69a6-4a18-b09f-5fd2a708059b",
        "sender": {
            "id": {
                "type": "CUSTOM",
                "val": "WCDP_ORUEN"
            },
            "dtime": "2024-03-20T13:10:08.3722639Z"
        },
        "origin": {
            "source": "backend",
            "dtime": "2024-03-20T14:37:15.0939400Z"
        },
        "vehicle": {
            "id": {
                "type": "vin",
                "val": "BVWCVWAUZ22053101"
            }
        },
        "updateEcosys": {
            "id": {
                "val": "e3-1.1-oru4"
            },
            "uc": {
                "id": {
                    "type": "custom",
                    "val": "upgrade"
                },
                "exec": {
                    "id": {
                        "val": "0"
                    }
                },
                "campaign": {
                    "id": {
                        "val": "RECALL_OUG6_A3_10001164_485DDF5413A04C2DAA40EF6892982D7F"
                    },
                    "recall": {
                        "action": {
                            "id": {
                                "val": "OUG6"
                            },
                            "criterion": {
                                "id": {
                                    "val": "A3"
                                }
                            }
                        }
                    },
                    "svc42ChangeMeasure": {
                        "id": {
                            "val": "003"
                        }
                    },
                    "batch": {
                        "id": {
                            "val": "485DDF5413A04C2DAA40EF6892982D7F"
                        }
                    }
                },
                "vehicleEvent": {
                    "key": "onboardPrepped",
                    "raw": "DL_SESSION_COMPLETED",
                    "message": {
                        "text": "the vehicle software was updated"
                    }
                }
            },
            "release": {
                "id": {
                    "val": "85H110100A"
                },
                "version": {
                    "val": "1015"
                },
                "notes": {
                    "id": {
                        "val": "rn-2023-09-06-test"
                    }
                }
            }
        }
    },
	{
        "schema": {
            "name": "updatestatus",
            "version": "1.1.3"
        },
        "brand": "vw",
        "market": "eu",
        "uuid": "15616ebe-1dfd-4f5c-b2ed-cea0ac1ad823",
        "sender": {
            "id": {
                "type": "CUSTOM",
                "val": "WCDP_ORUEN"
            },
            "dtime": "2024-03-20T13:10:08.3722639Z"
        },
        "origin": {
            "source": "backend",
            "dtime": "2024-03-20T14:37:15.0939400Z"
        },
        "vehicle": {
            "id": {
                "type": "vin",
                "val": "BVWCVWAUZ22053101"
            }
        },
        "updateEcosys": {
            "id": {
                "val": "e3-1.1-oru4"
            },
            "uc": {
                "id": {
                    "type": "custom",
                    "val": "upgrade"
                },
                "exec": {
                    "id": {
                        "val": "0"
                    }
                },
                "campaign": {
                    "id": {
                        "val": "RECALL_OUG6_A3_10001164_485DDF5413A04C2DAA40EF6892982D7F"
                    },
                    "recall": {
                        "action": {
                            "id": {
                                "val": "OUG6"
                            },
                            "criterion": {
                                "id": {
                                    "val": "A3"
                                }
                            }
                        }
                    },
                    "svc42ChangeMeasure": {
                        "id": {
                            "val": "003"
                        }
                    },
                    "batch": {
                        "id": {
                            "val": "485DDF5413A04C2DAA40EF6892982D7F"
                        }
                    }
                },
                "vehicleEvent": {
                    "key": "updated",
                    "raw": "INSTALLATION_COMPLETE_DP",
